### ISSUE TITLE
[Question] Edilkamin climate target temperature

### ISSUE THREAD

**Issue by jonathannaguin** [algra4/ha-edilkamin#22]
Hello,

Forgive my ignorance, but I have a question regarding the target temperature of the Edilkamin entity.
When the target temperature is reached while the heater is on... is it supposed to automatically shut down? or do we need to setup an automation to do so?
Asking because I've noticed some situations where the target is 20 degrees, reached 20.9 and the climate didn't turn off.

Thanks!

**Comment by algra4** [comment]
Hello @jonathannaguin, 

The integration does not change the stove's default behavior. 
So, when the stove reaches the expected temperature, it continues to operate. 

If you want to stop it when the temperature is reached, you can do so with an integration, but I don't know if this is good practice for your project. 
Asking your dealer could be the first step.

Good evening

**Comment by jonathannaguin** [comment]
Thanks for your response @algra4 , the Mind app has an option for setting an "auto" mode on which the stove automatically shutdowns when the environment temperature is reached (screenshot attached). The climate temperature configured in HA does not update this value nor there is an option to enable this mode, however I could replicate this behaviour with a simple automation. I was wondering if this is something HA would do for any climate entity. 

<img width="374" alt="image" src="https://github.com/user-attachments/assets/155e894b-9aa4-47d3-9bec-63641d39b331" />

**Comment by algra4** [comment]
Hello @jonathannaguin, 

I think that you talk about the standby mode.
![image](https://github.com/user-attachments/assets/78da7a5c-e4c9-46a3-aca3-72a6dffb3c72)


This feature has been release in [3.3.0](https://github.com/algra4/ha-edilkamin/releases/tag/v3.3.0)
