### ISSUE TITLE
Integration stopped working

### ISSUE THREAD

**Issue by miki3421** [algra4/ha-edilkamin#3]
Since the last HA update the integration is not working with this error.

Logger: homeassistant.config_entries
Source: custom_components/edilkamin/__init__.py:34
Integration: Edilkamin ([documentation](https://github.com/algra4/edilkamin))
First occurred: May 4, 2023 at 05:45:16 (1 occurrences)
Last logged: May 4, 2023 at 05:45:16

Error setting up entry 24d7eb71f518 for edilkamin
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/edilkamin/__init__.py", line 34, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by algra4** [comment]
Hello @miki3421, 

I fixed the problem in #4. 

I released a new version (v1.0.1), you need to update it in hacs or whatever
