### ISSUE TITLE
Impossibilité de trouver Client ID et Refresh Token

### ISSUE THREAD

**Issue by DomotiqueCLT** [algra4/ha-edilkamin#9]
Bonjour, 
Depuis la mise à jour d'hier, perte de connexion avec mon Feu Edilkamin Chéri Evo, qui jusque là fonctionnait à merveille. 

J'ai voulu configurer une nouvelle fois, hors je n'arrive pas à trouver le Refresh Token ainsi que Client ID malgré plusieurs essais, j'ai un message de Policy Privacy venant de l'application The Mind ... 

Avez vous une solution ? 
Je suis sur android, j'ai un iPhone de secours. 

Merci à vous.

**Comment by algra4** [comment]
Hello @DomotiqueCLT,

Etrange car le mise à jour n'a pas posé de problème chez moi.

Je viens de créer une nouvelle [pre-release](https://github.com/algra4/ha-edilkamin/releases/tag/V2.0.0-beta.1) qui simplifie l'authentification en utilisant le username et password à la place du refresh token et client id. 

Pouvez-vous me dire si ca fonctionne bien aussi de votre coté (il faudra reconfigurer un nouveau pont mais les entitiées restent les meme) ? 

Si oui, je mettrai cette release en stable

Merci d'avance

**Comment by DomotiqueCLT** [comment]
Bonjour 
Je viens de tester, ca fonctionne. 

Concernant les entités, quelques fonctions sont modifiés, comme le réglage du ventilateur, avant nous avions 1-5 + Auto maintenant nous avons plus le mode auto, tout comme le ventilateur auxiliaire que l'on ne peut plus régler de la même sorte. 

En tout cas merci de votre réactivité, très bon travail, grâce à vous, je vais pouvoir refaire fonctionner mon feu avec HA. 

Vous pouvez également mettre que votre intégration fonctionne avec les Chéri Evo 💪
